# Generated by Django 3.1 on 2021-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserstatus',
            name='status',
            field=models.CharField(choices=[('0', 'Invitation Send'), ('1', 'Approved'), ('2', 'Pending Approval'), ('3', 'Pendind Review'), ('4', 'Rejected'), ('5', 'Terminated')], default=2, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('0', 'Invitation Send'), ('1', 'Approved'), ('2', 'Pending Approval'), ('3', 'Pendind Review'), ('4', 'Rejected'), ('5', 'Terminated')], default=2, max_length=50, null=True),
        ),
    ]
