# Generated by Django 3.1 on 2021-09-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserstatus',
            name='updated_on',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserOnboardingTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboard_status', models.CharField(choices=[('0', 'Registered'), ('1', 'Approved'), ('2', 'Get Started'), ('4', 'Done')], default='0', max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
