# Generated by Django 3.1 on 2021-09-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210909_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useronboardingtracker',
            old_name='onboard_status',
            new_name='status',
        ),
    ]
