# Generated by Django 3.1 on 2021-09-08 08:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0002_auto_20210906_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserinvites',
            name='firm_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaluserstatus',
            name='updated_on',
            field=models.DateField(default=datetime.date(2021, 9, 8)),
        ),
        migrations.AlterField(
            model_name='userinvites',
            name='firm_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinvites_firm_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='updated_on',
            field=models.DateField(default=datetime.date(2021, 9, 8)),
        ),
    ]
