# Generated by Django 3.1 on 2021-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20210909_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboardingtracker',
            name='status',
            field=models.CharField(choices=[('0', 'Get Started'), ('1', 'Done')], default='0', max_length=50, null=True),
        ),
    ]
