# Generated by Django 3.1 on 2021-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_historicaluserdetails_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserdetails',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
