# Generated by Django 3.1 on 2021-09-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20210912_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
