# Generated by Django 3.1 on 2021-09-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20210912_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserdetails',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user_management.userstatus'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.userstatus'),
        ),
    ]
