# Generated by Django 3.1 on 2021-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='user_type',
            field=models.CharField(max_length=50, null=True, verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(max_length=50, null=True, verbose_name='User Type'),
        ),
    ]
