# Generated by Django 3.1 on 2021-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210908_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username'),
        ),
    ]
