# Generated by Django 3.1 on 2021-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210908_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='nnid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nnid',
            field=models.BigIntegerField(null=True),
        ),
    ]
