# Generated by Django 3.1 on 2021-09-06 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmname', models.CharField(max_length=100, null=True, unique=True)),
                ('firm_id', models.CharField(max_length=25, null=True, unique=True)),
                ('firm_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('firm_website', models.TextField(blank=True, null=True, unique=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('officephone', models.BigIntegerField(null=True, unique=True)),
                ('mobile', models.BigIntegerField(null=True, unique=True)),
                ('est_year', models.IntegerField(null=True)),
                ('register_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Firms',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFirms',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('firmname', models.CharField(db_index=True, max_length=100, null=True)),
                ('firm_id', models.CharField(db_index=True, max_length=25, null=True)),
                ('firm_email', models.EmailField(db_index=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('firm_website', models.TextField(blank=True, db_index=True, null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('officephone', models.BigIntegerField(db_index=True, null=True)),
                ('mobile', models.BigIntegerField(db_index=True, null=True)),
                ('est_year', models.IntegerField(null=True)),
                ('register_on', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical firms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFirmInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(default=2, max_length=50, null=True)),
                ('updated_on', models.DateField(default=datetime.date(2021, 9, 6))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('firmname', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='firm_management.firms')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical firm info',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FirmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=2, max_length=50, null=True)),
                ('updated_on', models.DateField(default=datetime.date(2021, 9, 6))),
                ('firmname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firminfo_firm_name', to='firm_management.firms')),
            ],
            options={
                'verbose_name_plural': 'Firm info',
            },
        ),
    ]
