# Generated by Django 3.1 on 2021-09-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm_management', '0002_auto_20210910_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmdetails',
            old_name='firm_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='historicalfirmdetails',
            old_name='firm_website',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='firmdetails',
            name='register_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmstatus',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalfirmdetails',
            name='register_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfirmstatus',
            name='updated_on',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
