# Generated by Django 3.1 on 2021-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm_management', '0003_auto_20210906_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmstatus',
            name='status',
            field=models.CharField(choices=[('0', 'Invitation Send'), ('1', 'Approved'), ('2', 'Pending Approval'), ('3', 'Pendind Review'), ('4', 'Rejected'), ('5', 'Terminated')], default=2, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfirmstatus',
            name='status',
            field=models.CharField(choices=[('0', 'Invitation Send'), ('1', 'Approved'), ('2', 'Pending Approval'), ('3', 'Pendind Review'), ('4', 'Rejected'), ('5', 'Terminated')], default=2, max_length=50, null=True),
        ),
    ]
