# Generated by Django 3.1 on 2021-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm_management', '0004_auto_20210910_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmdetails',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfirmdetails',
            name='website',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
