# Generated by Django 3.1 on 2021-09-07 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm_management', '0004_auto_20210906_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='firms',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfirms',
            name='last_login',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='firmstatus',
            name='updated_on',
            field=models.DateField(default=datetime.date(2021, 9, 8)),
        ),
        migrations.AlterField(
            model_name='historicalfirmstatus',
            name='updated_on',
            field=models.DateField(default=datetime.date(2021, 9, 8)),
        ),
    ]
