# Generated by Django 3.1 on 2021-09-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firm_management', '0005_auto_20210908_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalFirms',
        ),
    ]
