# Generated by Django 3.1 on 2021-09-08 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firm_management', '0008_firms_firmstatus_historicalfirms_historicalfirmstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmslist_firmname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
