# Generated by Django 3.1 on 2021-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm_management', '0010_auto_20210908_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmslist',
            name='firmname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
